# 안녕하세요! 이 파일은 tslint-to-eslint-config에 의해 자동 생성되었습니다.
# https://github.com/typescript-eslint/tslint-to-eslint-config
# 공식적으로 tslint는 @typescript-eslint/eslint-plugin으로 마이그레이션되었으므로,
# 최종적으로 이 구성을 기본으로 해서 확장하도록 이 구성을 전환할 것을 권장합니다.
# 이 파일은 이 프로젝트의 원래 TSLint 구성에 가장 근접한
# 프로젝트의 원래 TSLint 구성을 플로그인의 문법으로 변환했습니다.
# https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/FAQs.md
# 행복한 린팅! 💖
---
env:
  browser: true
  es6: true
  node: true
  commonjs: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@next/next/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:jest-dom/recommended
  - next/core-web-vitals
  - prettier
  - next
overrides:
  - files:
      - '**/__tests__/**/*.[jt]s?(x)'
      - '**/__mocks__/**/*.[jt]s?(x)'
      - '**/?(*.)+(spec|test).[jt]s?(x)'
    extends:
      - plugin:testing-library/react
  - files:
      - '**/*.ts?(x)'
    parser: '@typescript-eslint/parser'
    parserOptions:
      sourceType: module
      ecmaFeatures:
        jsx: true
      warnOnUnsupportedTypeScriptVersion: true
parser: '@typescript-eslint/parser'
settings:
  next:
    rootDir: .
  react:
    version: detect
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .mts
      - .cts
      - .tsx
      - .d.ts
  import/resolver:
    eslint-import-resolver-node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
    eslint-import-resolver-typescript:
      alwaysTryTypes: true
parserOptions:
  ecmaVersion: latest
  project: tsconfig.json
  sourceType: module
  tsconfigRootDir: ./
  requireConfigFile: false
  warnOnUnsupportedTypeScriptVersion: true
  allowImportExportEverywhere: true
  babelOptions:
    presets:
      - next/babel
    caller:
      supportsTopLevelAwait: true
  ecmaFeatures:
    jsx: true
plugins:
  - import
  - react
  - jsx-a11y
  - eslint-plugin-jsdoc
  - eslint-plugin-prefer-arrow
  - '@typescript-eslint'
root: true
rules:
  jest-dom/prefer-checked: error
  jest-dom/prefer-enabled-disabled: error
  jest-dom/prefer-required: error
  jest-dom/prefer-to-have-attribute: error
  '@typescript-eslint/type-annotation-spacing': error
  '@typescript-eslint/ban-ts-comment':
    - off
    - ts-expect-error: allow-with-description
      ts-ignore: allow-with-description
      ts-nocheck: allow-with-description
      ts-check: allow-with-description
  complexity:
    - error
    - max: 10
  eqeqeq:
    - error
    - allow-null
  id-denylist:
    - error
    - any
    - Number
    - number
    - String
    - string
    - Boolean
    - boolean
    - Undefined
    - undefined
  max-classes-per-file:
    - error
    - 1
  new-parens: warn
  no-case-declarations: warn
  no-console:
    - warn
    - allow:
        - debug
        - error
  no-dupe-args: warn
  no-dupe-class-members: warn
  no-mixed-spaces-and-tabs:
    - error
    - smart-tabs
  no-var: error
  no-with: error
  one-var:
    - error
    - never
  prefer-const: warn
  sort-imports:
    - warn
    - allowSeparatedGroups: true
      ignoreCase: false
      ignoreDeclarationSort: false
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
  spaced-comment:
    - error
    - always
    - markers:
        - /
  use-isnan: warn
  '@next/next/google-font-display': error
  '@next/next/google-font-preconnect': error
  '@next/next/inline-script-id': error
  '@next/next/next-script-for-ga': error
  '@next/next/no-assign-module-variable': error
  '@next/next/no-async-client-component': error
  '@next/next/no-before-interactive-script-outside-document': error
  '@next/next/no-css-tags': error
  '@next/next/no-document-import-in-page': error
  '@next/next/no-duplicate-head': error
  '@next/next/no-head-element': error
  '@next/next/no-head-import-in-document': error
  '@next/next/no-html-link-for-pages': error
  '@next/next/no-img-element': error
  '@next/next/no-page-custom-font': error
  '@next/next/no-script-component-in-head': error
  '@next/next/no-styled-jsx-in-document': error
  '@next/next/no-sync-scripts': error
  '@next/next/no-title-in-document-head': error
  '@next/next/no-typos': error
  '@next/next/no-unwanted-polyfillio': error
  import/no-anonymous-default-export: warn
  react/jsx-no-target-blank: off
  react/no-unescaped-entities: off
  react/no-unknown-property: off
  react/react-in-jsx-scope: off
  react/prop-types: off
  jsx-a11y/alt-text:
    - warn
    - elements:
        - img
      img:
        - Image
  jsx-a11y/aria-props: warn
  jsx-a11y/aria-proptypes: warn
  jsx-a11y/aria-unsupported-elements: warn
  jsx-a11y/role-has-required-aria-props: warn
  jsx-a11y/role-supports-aria-props: warn
