# WhatATheme
markdown: kramdown

# URL of the Site
url: ""
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: DongminYoo - Portfolio
# Description of the Site
description: Dongmin,Yoo - Developer.
# URL of Image of the Site
site-image: https://images.unsplash.com/photo-1484291470158-b8f8d608850d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.unsplash.com/photo-1520208422220-d12a3c588e6c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ydm2790@gmail.com
facebook_username: ydm2790
instagram_username: minzzi._.andrew
linkedin_username: dongmin-yu-0394a5223
github_username: AndrewDongminYoo
youtube_channel_id: UC0f92oThUd9CdSipnoiYR8g

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: DongminYoo

# Name of the Author
author-name: DongminYoo
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: 동료 간의 생산적인 비판과 의견에 항상 열린 태도를 가지고, 전반적인 사용자 경험의 향상을 위해 끊임없이 효율적인 구현과 개선을 고민하며, 적극적으로 주어진 문제를 해결하고 개선하려는 의지를 가지고 있습니다.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/AndrewDongminYoo

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
